theme: jekyll-theme-flexible  
title: Q's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I will share my knowledge and experience here.
  I hope you will find something useful for yourself.
  If you have any questions, please contact me via email or social networks.
  Thank you for visiting my blog.
  Have a nice day!
permalink: ':title/'
baseurl: "/toq-eng-blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: To Phu Quy # add your name
author-img: avatar.jpg # add your photo
about-author: I'm currently a student majoring SE in VNU-HCM UIT. # add description
social-twitter: toilet_1996
social-facebook: tophuquy.999 # add your Facebook handle
social-github: QT069 # add your Github handle
social-email: tophuquy2712@gmail.com


# Disqus
discus-identifier: toq # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
